title: "Rosie Pattern Language"
url: "http://rosie-lang.org" # the base hostname & protocol for your site
permalink: /blog/:year/:month/:day/:title
email: info@rosie-lang.org
twitter_username: jamietheriveter
github_username:  jamiejennings
#description: "This blog is under construction"
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-sitemap
  